name: CI

on:
  push:
    branches:
      - '**'
  #workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * *'
  
jobs:
  build_and_test:
    name: Build & unit test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test_coverage_report
          path: coverage
    
  docker:
    name: Docker build & push
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

#    needs: build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: ${ vars.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com
#          username: ${ secrets.AWS_ACCESS_KEY_ID }}
#          password: ${ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jtluoto/gh-actions-docker-demo  

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}