name: Publish to ghcr.io

on:
  push:
    branches:
      - '**'

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Example of how to run a shell command
        run: echo "Run build & unit tests"

      
  docker_build_and_publish:
    name: Docker build & publish
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    needs: run_tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Example of how to run a shell command
        run: echo "Run docker build & push"
